[platformio]

[env:lilygo-t-sim7080x-s3]
platform = espressif32@6.3.0
framework = arduino
board = esp32s3box

upload_speed = 921600
monitor_speed = 115200

build_flags =
    -DBOARD_HAS_PSRAM       

    ; Habilitamos el USB nativo y el CDC en el arranque
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

    -DTINY_GSM_MODEM_SIM7080
    -DTINY_GSM_RX_BUFFER=1024
    -DCAYENNE_PRINT=Serial
    -DDUMP_AT_COMMANDS
    -DCONFIG_BT_BLE_50_FEATURES_SUPPORTED
